# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1qFsZ-VsWKNI76laHKFaUFJBobiZoxl
"""

import time

times = []
for i in range(10):
    start = time.time()
    time.sleep(0.2)
    times.append(time.time() - start)

print("Average response time:", sum(times)/len(times))

import os
os.system("ping -c 5 google.com")

import time

start = time.time()
time.sleep(0.2)  # Simulated network delay
end = time.time()

print("Response time:", end - start)